# Generated by Django 4.0.4 on 2022-12-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('comment', models.CharField(blank=True, max_length=15)),
                ('categoriya', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
